### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by ericgaspar**
- Add templates

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by alexAubin** [comment]
My god that's a very stupid bug ...

Internally `ynh_user_delete` uses `getent passwd $username` to check if the user exists ... But `getent`, when receiving a numeric username, assumes that it's a uid instead of the username and looks for a user with uid 243 (in our case) which most probably doesnt exists ...

Dunno what to do to fix this ...

**Comment by ericgaspar** [comment]
> Dunno what to do to fix this ...

Rename the app `deux-cent-quarante-trois` 😬

**Comment by ericgaspar** [comment]
!testme

**Pull request closed without merging**
